### ISSUE TITLE
Error 500 Headers are immutable.

### ISSUE THREAD

**Issue by jupegarnica** [satyarohith/sift#21]
FYI
serveStatic fails serving a plain .html. 

Error serving request: TypeError: Headers are immutable.
    at Headers.set (deno:op_crates/fetch/20_headers.js:348:15)
    at Object./screen (https://deno.land/x/sift@0.3.0/mod.ts:126:41)
    at async handleRequest (https://deno.land/x/sift@0.3.0/mod.ts:48:36)
    at async respondWith (deno:js/10_sr.js:58:14)

**Comment by jupegarnica** [comment]
but works fine locally
