### ISSUE TITLE
Use Deno.readFile for static files

### ISSUE THREAD

**Issue by ry** [satyarohith/sift#33]

**Comment by hashrock** [comment]
I got this error in Deno Deploy.
Is this error related to this Issue?

```
GET /deno.png 2ms 500
Error serving request: TypeError: scheme 'file' not supported
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at opFetch (deno:ext/fetch/26_fetch.js:57:17)
    at mainFetch (deno:ext/fetch/26_fetch.js:199:61)
    at deno:ext/fetch/26_fetch.js:439:11
    at new Promise (<anonymous>)
    at fetch (deno:ext/fetch/26_fetch.js:399:15)
    at Object./deno.png (https://deno.land/x/sift@0.3.5/mod.ts:138:30)
    at async handleRequest (https://deno.land/x/sift@0.3.5/mod.ts:63:36)
```

It doesn't happen with deployctl, but it does when I deploy to deno deploy.

https://github.com/hashrock-sandbox/study-deploy-sift/blob/master/main.ts#L4
